require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ExcursionsController do

  # This should return the minimal set of attributes required to create a valid
  # Excursion. As you add validations to Excursion, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all excursions as @excursions" do
      excursion = Excursion.create! valid_attributes
      get :index
      assigns(:excursions).should eq([excursion])
    end
  end

  describe "GET show" do
    it "assigns the requested excursion as @excursion" do
      excursion = Excursion.create! valid_attributes
      get :show, :id => excursion.id.to_s
      assigns(:excursion).should eq(excursion)
    end
  end

  describe "GET new" do
    it "assigns a new excursion as @excursion" do
      get :new
      assigns(:excursion).should be_a_new(Excursion)
    end
  end

  describe "GET edit" do
    it "assigns the requested excursion as @excursion" do
      excursion = Excursion.create! valid_attributes
      get :edit, :id => excursion.id.to_s
      assigns(:excursion).should eq(excursion)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Excursion" do
        expect {
          post :create, :excursion => valid_attributes
        }.to change(Excursion, :count).by(1)
      end

      it "assigns a newly created excursion as @excursion" do
        post :create, :excursion => valid_attributes
        assigns(:excursion).should be_a(Excursion)
        assigns(:excursion).should be_persisted
      end

      it "redirects to the created excursion" do
        post :create, :excursion => valid_attributes
        response.should redirect_to(Excursion.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved excursion as @excursion" do
        # Trigger the behavior that occurs when invalid params are submitted
        Excursion.any_instance.stub(:save).and_return(false)
        post :create, :excursion => {}
        assigns(:excursion).should be_a_new(Excursion)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Excursion.any_instance.stub(:save).and_return(false)
        post :create, :excursion => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested excursion" do
        excursion = Excursion.create! valid_attributes
        # Assuming there are no other excursions in the database, this
        # specifies that the Excursion created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Excursion.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => excursion.id, :excursion => {'these' => 'params'}
      end

      it "assigns the requested excursion as @excursion" do
        excursion = Excursion.create! valid_attributes
        put :update, :id => excursion.id, :excursion => valid_attributes
        assigns(:excursion).should eq(excursion)
      end

      it "redirects to the excursion" do
        excursion = Excursion.create! valid_attributes
        put :update, :id => excursion.id, :excursion => valid_attributes
        response.should redirect_to(excursion)
      end
    end

    describe "with invalid params" do
      it "assigns the excursion as @excursion" do
        excursion = Excursion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Excursion.any_instance.stub(:save).and_return(false)
        put :update, :id => excursion.id.to_s, :excursion => {}
        assigns(:excursion).should eq(excursion)
      end

      it "re-renders the 'edit' template" do
        excursion = Excursion.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Excursion.any_instance.stub(:save).and_return(false)
        put :update, :id => excursion.id.to_s, :excursion => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested excursion" do
      excursion = Excursion.create! valid_attributes
      expect {
        delete :destroy, :id => excursion.id.to_s
      }.to change(Excursion, :count).by(-1)
    end

    it "redirects to the excursions list" do
      excursion = Excursion.create! valid_attributes
      delete :destroy, :id => excursion.id.to_s
      response.should redirect_to(excursions_url)
    end
  end

end
